POST http://localhost:8000/api/bot/username
Content-Type: application/json
Accept: application/json

{
    "mamali": "salam"
}


### Channel Post
POST http://localhost:8000/api/bot/username
Content-Type: application/json
Accept: application/json

{
  "update_id": 233934469,
  "channel_post": {
    "message_id": 12,
    "sender_chat": {
      "id": -1001948242822,
      "title": "ai pair",
      "username": "AIPair",
      "type": "channel"
    },
    "chat": {
      "id": -1001948242822,
      "title": "ai pair",
      "username": "AIPair",
      "type": "channel"
    },
    "date": 1692291426,
    "text": "⏰ یادآوری برای نوشتن"
  }
}

### Group Message
POST http://localhost:8000/api/bot/username
Content-Type: application/json
Accept: application/json

{
  "update_id": 233934472,
  "message": {
    "message_id": 7,
    "from": {
      "id": 69221229,
      "is_bot": false,
      "first_name": "» мr.мαнαɴ",
      "username": "adeveloper",
      "language_code": "en",
      "is_premium": true
    },
    "chat": {
      "id": -652973741,
      "title": "بک آپ",
      "type": "group",
      "all_members_are_administrators": true
    },
    "date": 1692372276,
    "text": "salam"
  }
}

### Private Message
POST http://localhost:8000/api/bot/username
Content-Type: application/json
Accept: application/json

{
    "update_id": 233934476,
    "message": {
        "message_id": 9,
        "from": {
            "id": 69221229,
            "is_bot": false,
            "first_name": "» мr.мαнαɴ",
            "username": "adeveloper",
            "language_code": "en",
            "is_premium": true
        },
        "chat": {
            "id": 69221229,
            "first_name": "» мr.мαнαɴ",
            "username": "adeveloper",
            "type": "private"
        },
        "date": 1692519408,
        "text": "salam"
    }
}

### My Chat Member
POST http://localhost:8000/api/bot/username
Content-Type: application/json
Accept: application/json

{
  "update_id": 233934470,
  "my_chat_member": {
    "chat": {
      "id": -652973741,
      "title": "بک آپ",
      "type": "group",
      "all_members_are_administrators": true
    },
    "from": {
      "id": 69221229,
      "is_bot": false,
      "first_name": "» мr.мαнαɴ",
      "username": "adeveloper",
      "language_code": "en",
      "is_premium": true
    },
    "date": 1692371553,
    "old_chat_member": {
      "user": {
        "id": 283598419,
        "is_bot": true,
        "first_name": "MihanAds",
        "username": "MihanAds_bot"
      },
      "status": "left"
    },
    "new_chat_member": {
      "user": {
        "id": 283598419,
        "is_bot": true,
        "first_name": "MihanAds",
        "username": "MihanAds_bot"
      },
      "status": "member"
    }
  }
}
